# サイトのURL設定（自分のユーザー名に合わせてください）
url: "https://shunchama.github.io"
baseurl: "" # ここを空にすることで、ルートからの絶対パスが有効になります

remote_theme: just-the-docs/just-the-docs

# 基本情報
title: shunchama's Portal Site
description: 趣味の話を中心に投稿しています

# 外部からの読み込みを安定させる
plugins:
  - jekyll-remote-theme

# 配色設定（darkを指定しつつ、後ほどCSSで#000000に追い込みます）
color_scheme: dark

# リンク設定
aux_links:
  "GitHub": "https://github.com/shunchama"

mathjax: true

future: true
timezone: Asia/Tokyo
